### ISSUE TITLE
Type *Entity* is not assignable to type Constructable<*Entity*>

### ISSUE THREAD

**Issue by ludgerey** [jorgebodega/typeorm-factory#166]
When trying to recreate the examples from README, I get a type error.

Factory:
```ts
export class EquipmentFactory extends Factory<EquipmentsEntity> {
  protected entity: EquipmentsEntity; // <-- here
  protected dataSource: DataSource;
  protected attrs(): FactorizedAttrs<EquipmentsEntity> {
    return {
      title: faker.vehicle.vehicle(),
      // [...]
    };
  }
}
```

The error:
```
Type EquipmentsEntity is not assignable to type Constructable<EquipmentsEntity>
```

Of cause I tried wrapping the Entity with `Constructable`, but this results in a runtime error, when used as following:

```ts
await new EquipmentFactory().create();
```

Results in 
```
this.entity is not a constructor
TypeError: this.entity is not a constructor
    at EquipmentFactory.makeEntity (.../node_modules/@jorgebodega/typeorm-factory/src/factory.ts:69:20)
    at EquipmentFactory.create (.../factory.ts:43:31)
 [...]
```

How to solve this? Is this a bug? At least it varies from the README.

Versions:
```
├── @jorgebodega/typeorm-factory@1.4.0
├── @nestjs/core@10.3.3
├── @nestjs/typeorm@10.0.2
├── ts-node@10.9.2
├── typeorm@0.3.20
├── typescript@5.3.3
```

**Comment by jorgebodega** [comment]
Without a proper example with the code, I cannot do much.

Can you try to upload a simple repo with the case?

**Comment by ludgerey** [comment]
Sorry, I totally missed that slight difference. This solved it!
